# Generated by Django 2.0 on 2018-12-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('passW', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('nameUsuario', models.CharField(max_length=20, verbose_name='Nombre')),
                ('surnameUsuario', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('genreUsuario', models.CharField(max_length=40, verbose_name='Genero')),
                ('paisUsuario', models.CharField(max_length=40, verbose_name='Pais de origen')),
                ('dateUsuario', models.CharField(max_length=40, verbose_name='Fecha de Nacimiento')),
            ],
        ),
    ]
