# Generated by Django 2.0 on 2019-01-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190129_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('DK/NA', 'DK/NA')], default='DK/NA', max_length=500),
        ),
    ]
